/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mudarede;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Vanderlei
 */
public class Tela extends javax.swing.JFrame {

    ArrayList<String> netshToList; 
    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        netshToList = new ArrayList<String>();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btMudar = new javax.swing.JButton();
        cbTipo = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        lblIP = new javax.swing.JLabel();
        lblMascara = new javax.swing.JLabel();
        lblGateway = new javax.swing.JLabel();
        lblDNS = new javax.swing.JLabel();
        lblDHCP = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbIPAtual = new javax.swing.JTable();
        lblClose = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Net Config");
        setBackground(new java.awt.Color(102, 0, 102));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btMudar.setBackground(Color.decode("#4C0B5F"));
        btMudar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btMudar.setForeground(new java.awt.Color(204, 204, 204));
        btMudar.setText("Mudar");
        btMudar.setBorder(null);
        btMudar.setBorderPainted(false);
        btMudar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btMudar.setPreferredSize(new java.awt.Dimension(40, 15));
        btMudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMudarActionPerformed(evt);
            }
        });

        cbTipo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estático 1", "Estático 2", "DHCP" }));
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        lblIP.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblIP.setForeground(new java.awt.Color(255, 255, 255));
        lblIP.setText("jLabel1");

        lblMascara.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblMascara.setForeground(new java.awt.Color(255, 255, 255));
        lblMascara.setText("jLabel1");

        lblGateway.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblGateway.setForeground(new java.awt.Color(255, 255, 255));
        lblGateway.setText("jLabel1");

        lblDNS.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDNS.setForeground(new java.awt.Color(255, 255, 255));
        lblDNS.setText("jLabel1");

        lblDHCP.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblDHCP.setForeground(new java.awt.Color(255, 255, 255));
        lblDHCP.setText("DHCP: off");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIP)
                    .addComponent(lblMascara)
                    .addComponent(lblGateway)
                    .addComponent(lblDNS)
                    .addComponent(lblDHCP, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMascara)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblGateway)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDNS)
                .addGap(18, 18, 18)
                .addComponent(lblDHCP)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Escolha suas configurações de rede");

        jButton1.setBackground(Color.decode("#4C0B5F")
        );
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Atualizar configurações locais");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton1MouseMoved(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tbIPAtual.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbIPAtual.setForeground(new java.awt.Color(153, 0, 153));
        tbIPAtual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Endereço IP", null},
                {"Máscara de sub-rede", null},
                {"Gateway", null},
                {"Servidor DNS", null}
            },
            new String [] {
                "Configurações locais", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbIPAtual.setGridColor(new java.awt.Color(0, 204, 102));
        tbIPAtual.setIntercellSpacing(new java.awt.Dimension(2, 2));
        tbIPAtual.setName(""); // NOI18N
        jScrollPane2.setViewportView(tbIPAtual);

        lblClose.setFont(new java.awt.Font("Estrangelo Edessa", 1, 18)); // NOI18N
        lblClose.setForeground(java.awt.Color.gray);
        lblClose.setText("X");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
        });

        lblMinimize.setFont(new java.awt.Font("Estrangelo Edessa", 1, 18)); // NOI18N
        lblMinimize.setForeground(java.awt.Color.gray);
        lblMinimize.setText("_");
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(96, 385, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btMudar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMinimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClose)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClose)
                    .addComponent(lblMinimize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btMudar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbTipo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMudarActionPerformed
        // TODO add your handling code here:
        executaComando();
    }//GEN-LAST:event_btMudarActionPerformed

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
        // TODO add your handling code here:
        atualizaPainel();
    }//GEN-LAST:event_cbTipoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        atualizaPainel();
        obtainAddresses();    
        this.getContentPane().setBackground(Color.decode("#4C0B5F"));
        //JTableHeader header = tbIPAtual.getTableHeader();
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        obtainAddresses();        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseMoved
        // TODO add your handling code here:        
    }//GEN-LAST:event_jButton1MouseMoved

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(Tela.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        // TODO add your handling code here:
        lblClose.setForeground(Color.white);
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        // TODO add your handling code here:
        lblClose.setForeground(Color.gray);
    }//GEN-LAST:event_lblCloseMouseExited

    private void lblMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseEntered
        // TODO add your handling code here:
        lblMinimize.setForeground(Color.white);
    }//GEN-LAST:event_lblMinimizeMouseEntered

    private void lblMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseExited
        // TODO add your handling code here:
        lblMinimize.setForeground(Color.gray);
    }//GEN-LAST:event_lblMinimizeMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMudar;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDHCP;
    private javax.swing.JLabel lblDNS;
    private javax.swing.JLabel lblGateway;
    private javax.swing.JLabel lblIP;
    private javax.swing.JLabel lblMascara;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JTable tbIPAtual;
    // End of variables declaration//GEN-END:variables

    private void atualizaPainel() {
        switch(cbTipo.getSelectedIndex()){
            case 0 :
                lblIP.setText("192.168.1.220");
                lblMascara.setText("255.255.255.0");
                lblGateway.setText("192.168.1.1");
                lblDNS.setText("192.168.1.1");
                lblDHCP.setText("IP estático");                
                break;
                case 1 :
                lblIP.setText("192.168.1.220");
                lblMascara.setText("255.255.255.0");
                lblGateway.setText("192.168.1.2");
                lblDNS.setText("192.168.1.2");
                lblDHCP.setText("IP estático");                
                break;
                case 2 :
                lblIP.setText("xxx.xxx.xxx.xxx");
                lblMascara.setText("xxx.xxx.xxx.xxx");
                lblGateway.setText("xxx.xxx.xxx.xxx");
                lblDNS.setText("xxx.xxx.xxx.xxx");
                lblDHCP.setText("DHCP: on");                
                break;
            
        }
    }
    private void executaComando(){
        String gateway1 = "netsh interface ip set address name = \"OffBoard\" static 192.168.1.220 255.255.255.0 192.168.1.1";
        String dns1 = "netsh interface ip set dnsservers name=\"OffBoard\" static 192.168.1.1 primary no";
        String gateway2 = "netsh interface ip set address name = \"OffBoard\" static 192.168.1.220 255.255.255.0 192.168.1.2";
        String dns2 = "netsh interface ip set dnsservers name=\"OffBoard\" static 192.168.1.2 primary no";
        String dhcp = "netsh interface ip set address name=\"OffBoard\" dhcp";
        String dhcpDNS = "netsh interface ip set dnsservers name=\"OffBoard\" dhcp";
                
        switch(cbTipo.getSelectedIndex()){
            case 0 :
                try {
                    Runtime.getRuntime().exec(gateway1);
                    Runtime.getRuntime().exec(dns1);
            
                } catch (Exception e) {            
                }
                break;
                case 1 :
                try {
                    Runtime.getRuntime().exec(gateway2);
                    Runtime.getRuntime().exec(dns2);
            
                } catch (Exception e) {            
                }
                break;
                case 2 :
                try {
                    Runtime.getRuntime().exec(dhcp);
                    Runtime.getRuntime().exec(dhcpDNS);
            
                } catch (Exception e) {            
                }                
                break;
            
        }
    }

    private void obtainAddresses() {
        
        IPAddress ip = new IPAddress();
        String address = "";
        String gateway = "";
        String dns = "";
        String mask = "";
        
        try {
            Process process = Runtime.getRuntime().exec("ipconfig /all");
            process.waitFor();

        BufferedReader reader = 
        new BufferedReader(new InputStreamReader(process.getInputStream(), "CP850"));
            
            String line = "";           
            
            while ((line = reader.readLine())!= null) {                    
                address = ip.getAdressIP(line);
                gateway = ip.getGateway(line);
                dns = ip.getDNS(line);
                mask = ip.getMask(line);                
                
                //MOSTRA AS INFORMAÇOES DO COMANDO MSDOS
                System.out.println(line);
                netshToList.add(line);     
                //TODO: trabalhar com arraylist
            }            
            
            tbIPAtual.setValueAt(address, 0, 1);
            tbIPAtual.setValueAt(mask, 1, 1);
            tbIPAtual.setValueAt(gateway, 2, 1);
            tbIPAtual.setValueAt(dns, 3, 1);            
        } 
        catch (Exception e) {
        }
    }
}
