/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mudarede;

import Config.Propriedades;

import java.awt.Color;
import java.awt.Component;
import java.awt.KeyboardFocusManager;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import jdk.nashorn.internal.ir.BreakNode;

/**
 *
 * @author Vanderlei
 */
public class Tela extends javax.swing.JFrame {

    ArrayList<String> netshToList; 
    ArrayList<Integer> netshIndex;
    private String adapterName;
    
    int posX=0,posY=0;//for dragg form
    
    ButtonFX fx;
    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        
        netshToList = new ArrayList<>();
        netshIndex = new ArrayList<>();
        this.setLocationRelativeTo(null);
        fx = new ButtonFX();
        
        this.addMouseListener(new MouseAdapter(){
            public void mousePressed(MouseEvent e){
                posX=e.getX();
                posY=e.getY();
            }
        });
        
        this.addMouseMotionListener(new MouseAdapter(){
            public void mouseDragged(MouseEvent evt){
		//sets frame position when mouse dragged			
		setLocation (evt.getXOnScreen()-posX,evt.getYOnScreen()-posY);					
            }
        });        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btMudar = new javax.swing.JButton();
        cbTipo = new javax.swing.JComboBox<>();
        lblClose = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblObter = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtIP1 = new javax.swing.JFormattedTextField();
        txtIP2 = new javax.swing.JFormattedTextField();
        txtIP4 = new javax.swing.JFormattedTextField();
        txtIP3 = new javax.swing.JFormattedTextField();
        txtIP5 = new javax.swing.JFormattedTextField();
        txtIP6 = new javax.swing.JFormattedTextField();
        txtIP7 = new javax.swing.JFormattedTextField();
        txtIP8 = new javax.swing.JFormattedTextField();
        txtIP9 = new javax.swing.JFormattedTextField();
        txtIP10 = new javax.swing.JFormattedTextField();
        txtIP11 = new javax.swing.JFormattedTextField();
        txtIP12 = new javax.swing.JFormattedTextField();
        txtIP13 = new javax.swing.JFormattedTextField();
        txtIP14 = new javax.swing.JFormattedTextField();
        txtIP15 = new javax.swing.JFormattedTextField();
        txtIP16 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblConfigAtual = new javax.swing.JLabel();
        txtNetworkName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Net Config");
        setBackground(new java.awt.Color(102, 0, 102));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btMudar.setBackground(Color.decode("#4C0B5F"));
        btMudar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btMudar.setForeground(new java.awt.Color(204, 204, 204));
        btMudar.setText("Confirma");
        btMudar.setBorder(null);
        btMudar.setBorderPainted(false);
        btMudar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btMudar.setPreferredSize(new java.awt.Dimension(40, 15));
        btMudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMudarActionPerformed(evt);
            }
        });

        cbTipo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Configuração atual", "Personalizado 1", "Personalizado 2", "DHCP" }));
        cbTipo.setBorder(null);
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });

        lblClose.setFont(new java.awt.Font("Estrangelo Edessa", 1, 18)); // NOI18N
        lblClose.setForeground(java.awt.Color.gray);
        lblClose.setText("X");
        lblClose.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
        });

        lblMinimize.setFont(new java.awt.Font("Estrangelo Edessa", 1, 18)); // NOI18N
        lblMinimize.setForeground(java.awt.Color.gray);
        lblMinimize.setText("_");
        lblMinimize.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseExited(evt);
            }
        });

        lblObter.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblObter.setForeground(new java.awt.Color(204, 153, 255));
        lblObter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObter.setText("Escolha suas configurações de rede");
        lblObter.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        lblObter.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblObter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblObterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblObterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblObterMouseExited(evt);
            }
        });

        txtIP1.setColumns(3);
        try {
            txtIP1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtIP1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIP1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIP1KeyReleased(evt);
            }
        });

        txtIP2.setColumns(3);
        try {
            txtIP2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtIP2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIP2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIP2KeyReleased(evt);
            }
        });

        txtIP4.setColumns(3);
        try {
            txtIP4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtIP4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIP4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIP4KeyReleased(evt);
            }
        });

        txtIP3.setColumns(3);
        try {
            txtIP3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtIP3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIP3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIP3KeyReleased(evt);
            }
        });

        txtIP5.setColumns(3);
        try {
            txtIP5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtIP5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIP5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIP5KeyReleased(evt);
            }
        });

        txtIP6.setColumns(3);
        try {
            txtIP6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtIP6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIP6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIP6KeyReleased(evt);
            }
        });

        txtIP7.setColumns(3);
        try {
            txtIP7.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtIP7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIP7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIP7KeyReleased(evt);
            }
        });

        txtIP8.setColumns(3);
        try {
            txtIP8.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtIP8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIP8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIP8KeyReleased(evt);
            }
        });

        txtIP9.setColumns(3);
        try {
            txtIP9.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtIP9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIP9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIP9KeyReleased(evt);
            }
        });

        txtIP10.setColumns(3);
        try {
            txtIP10.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtIP10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIP10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIP10KeyReleased(evt);
            }
        });

        txtIP11.setColumns(3);
        try {
            txtIP11.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtIP11.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIP11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIP11KeyReleased(evt);
            }
        });

        txtIP12.setColumns(3);
        try {
            txtIP12.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtIP12.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIP12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIP12KeyReleased(evt);
            }
        });

        txtIP13.setColumns(3);
        try {
            txtIP13.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtIP13.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIP13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIP13KeyReleased(evt);
            }
        });

        txtIP14.setColumns(3);
        try {
            txtIP14.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtIP14.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIP14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIP14KeyReleased(evt);
            }
        });

        txtIP15.setColumns(3);
        try {
            txtIP15.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtIP15.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIP15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIP15KeyReleased(evt);
            }
        });

        txtIP16.setColumns(3);
        try {
            txtIP16.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtIP16.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIP16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIP16KeyReleased(evt);
            }
        });

        jLabel1.setText("Endereço IP:");

        jLabel3.setText("Máscara:");

        jLabel4.setText("Gateway:");

        jLabel5.setText("Servidor DNS:");

        lblConfigAtual.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lblConfigAtual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConfigAtual.setText("Configuração atual");

        txtNetworkName.setEditable(false);
        txtNetworkName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNetworkName.setMargin(new java.awt.Insets(1, 1, 1, 1));

        jLabel2.setText("Nome do adaptador:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblConfigAtual)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(txtIP5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIP6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIP7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIP8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(txtIP9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIP10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIP11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIP12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtIP13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIP14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIP15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIP16, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(txtIP1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtIP2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtIP3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtIP4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtNetworkName, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblConfigAtual)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNetworkName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIP5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIP6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIP7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIP8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIP9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIP10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIP11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIP12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIP13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIP14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIP15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIP16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btMudar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblObter)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(lblMinimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClose)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblClose)
                            .addComponent(lblMinimize))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblObter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btMudar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMudarActionPerformed
        // TODO add your handling code here:
        executaComando();
    }//GEN-LAST:event_btMudarActionPerformed

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
        // TODO add your handling code here:
        atualizaPainel();
        changeEditable();        
    }//GEN-LAST:event_cbTipoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        atualizaPainel();
        obtainAddresses();    
        this.getContentPane().setBackground(Color.decode("#4C0B5F"));
        //JTableHeader header = tbIPAtual.getTableHeader();
        
    }//GEN-LAST:event_formWindowOpened

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(Tela.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        // TODO add your handling code here:
        lblClose.setForeground(Color.white);
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        // TODO add your handling code here:
        lblClose.setForeground(Color.gray);
    }//GEN-LAST:event_lblCloseMouseExited

    private void lblMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseEntered
        // TODO add your handling code here:
        lblMinimize.setForeground(Color.white);
    }//GEN-LAST:event_lblMinimizeMouseEntered

    private void lblMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseExited
        // TODO add your handling code here:
        lblMinimize.setForeground(Color.gray);
    }//GEN-LAST:event_lblMinimizeMouseExited

    private void lblObterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblObterMouseEntered
        // TODO add your handling code here:
        fx.setEnterColor(lblObter);
    }//GEN-LAST:event_lblObterMouseEntered

    private void lblObterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblObterMouseExited
        // TODO add your handling code here:
        fx.setExitColor(lblObter);
    }//GEN-LAST:event_lblObterMouseExited

    private void lblObterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblObterMouseClicked
        // TODO add your handling code here:
        obtainAddresses();         
    }//GEN-LAST:event_lblObterMouseClicked

    private void txtIP1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIP1KeyReleased
        // TODO add your handling code here:
        changeFocus(txtIP1);        
    }//GEN-LAST:event_txtIP1KeyReleased

    private void txtIP2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIP2KeyReleased
        // TODO add your handling code here:
        changeFocus(txtIP2);
    }//GEN-LAST:event_txtIP2KeyReleased

    private void txtIP4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIP4KeyReleased
        // TODO add your handling code here:
        changeFocus(txtIP4);
    }//GEN-LAST:event_txtIP4KeyReleased

    private void txtIP3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIP3KeyReleased
        // TODO add your handling code here:
        changeFocus(txtIP3);
        
    }//GEN-LAST:event_txtIP3KeyReleased

    private void txtIP5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIP5KeyReleased
        // TODO add your handling code here:
        changeFocus(txtIP5);
    }//GEN-LAST:event_txtIP5KeyReleased

    private void txtIP6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIP6KeyReleased
        // TODO add your handling code here:
        changeFocus(txtIP6);
    }//GEN-LAST:event_txtIP6KeyReleased

    private void txtIP7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIP7KeyReleased
        // TODO add your handling code here:
        changeFocus(txtIP7);
    }//GEN-LAST:event_txtIP7KeyReleased

    private void txtIP8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIP8KeyReleased
        // TODO add your handling code here:
        changeFocus(txtIP8);
    }//GEN-LAST:event_txtIP8KeyReleased

    private void txtIP9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIP9KeyReleased
        // TODO add your handling code here:
        changeFocus(txtIP9);
    }//GEN-LAST:event_txtIP9KeyReleased

    private void txtIP10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIP10KeyReleased
        // TODO add your handling code here:
        changeFocus(txtIP10);
    }//GEN-LAST:event_txtIP10KeyReleased

    private void txtIP11KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIP11KeyReleased
        // TODO add your handling code here:
        changeFocus(txtIP11);
    }//GEN-LAST:event_txtIP11KeyReleased

    private void txtIP12KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIP12KeyReleased
        // TODO add your handling code here:
        changeFocus(txtIP12);
    }//GEN-LAST:event_txtIP12KeyReleased

    private void txtIP13KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIP13KeyReleased
        // TODO add your handling code here:
        changeFocus(txtIP13);
    }//GEN-LAST:event_txtIP13KeyReleased

    private void txtIP14KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIP14KeyReleased
        // TODO add your handling code here:
        changeFocus(txtIP14);
    }//GEN-LAST:event_txtIP14KeyReleased

    private void txtIP15KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIP15KeyReleased
        // TODO add your handling code here:
        changeFocus(txtIP15);
    }//GEN-LAST:event_txtIP15KeyReleased

    private void txtIP16KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIP16KeyReleased
        // TODO add your handling code here:
        changeFocus(txtIP16);
    }//GEN-LAST:event_txtIP16KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMudar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblConfigAtual;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblObter;
    private javax.swing.JFormattedTextField txtIP1;
    private javax.swing.JFormattedTextField txtIP10;
    private javax.swing.JFormattedTextField txtIP11;
    private javax.swing.JFormattedTextField txtIP12;
    private javax.swing.JFormattedTextField txtIP13;
    private javax.swing.JFormattedTextField txtIP14;
    private javax.swing.JFormattedTextField txtIP15;
    private javax.swing.JFormattedTextField txtIP16;
    private javax.swing.JFormattedTextField txtIP2;
    private javax.swing.JFormattedTextField txtIP3;
    private javax.swing.JFormattedTextField txtIP4;
    private javax.swing.JFormattedTextField txtIP5;
    private javax.swing.JFormattedTextField txtIP6;
    private javax.swing.JFormattedTextField txtIP7;
    private javax.swing.JFormattedTextField txtIP8;
    private javax.swing.JFormattedTextField txtIP9;
    private javax.swing.JTextField txtNetworkName;
    // End of variables declaration//GEN-END:variables

    private void atualizaPainel() {
        Propriedades prop = new Propriedades();
        String address;
        String mask;
        String gateway;
        String dns;
        
        switch(cbTipo.getSelectedIndex()){
            case 0:
                obtainAddresses();
                lblConfigAtual.setText("Configuração atual");
                jPanel2.setBackground(Color.decode("#F0F0F0"));
                break;
            case 1 :      
                address = prop.getIp_1();
                mask = prop.getMask_1();
                gateway = prop.getGateway_1();
                dns = prop.getDns_1();
                
                fillTextBoxes(address, mask, gateway, dns);
                lblConfigAtual.setText("Configuração personalizada 1");                
                jPanel2.setBackground(Color.orange);
                break;
                case 2 :
                address = prop.getIp_2();
                mask = prop.getMask_2();
                gateway = prop.getGateway_2();
                dns = prop.getDns_2();
                
                fillTextBoxes(address, mask, gateway, dns);                
                lblConfigAtual.setText("Configuração Personalizada 2");
                jPanel2.setBackground(Color.PINK);
                break;
                case 3 :              
                  lblConfigAtual.setText("Configuração automática");
                  obtainAddresses();
                  jPanel2.setBackground(Color.YELLOW);
                break;
            
        }
    }
    private void executaComando(){
        String ipAddresses;
        String dnsAddress;
        
        String[] customIPs = getTextBoxesContent();        
        
        Netsh netsh = new Netsh(adapterName);
        netsh.setStaticAddress(customIPs);
        ipAddresses = netsh.getNetshIP();
        dnsAddress = netsh.getNetshDNS();        
                
        switch(cbTipo.getSelectedIndex()){
            case 1 ://Personalizado 1
                try {
                    System.out.println("Comando Netsh: \r\n" + ipAddresses + "\r\n" + dnsAddress);
                    Runtime.getRuntime().exec(ipAddresses);
                    Runtime.getRuntime().exec(dnsAddress);
            
                } catch (Exception e) {            
                }
                break;
                case 2 : //Personalizado 2
                try {
                    System.out.println("Netsh out: " + ipAddresses + "\r\n" + dnsAddress);
                    Runtime.getRuntime().exec(ipAddresses);
                    Runtime.getRuntime().exec(dnsAddress);
            
                } catch (Exception e) {            
                }
                break;
                case 3 : //DHCP
                    netsh.setDHCP();
                    ipAddresses = netsh.getNetshIP();
                    dnsAddress = netsh.getNetshDNS(); 
                    System.out.println("Netsh out: " + ipAddresses + "\r\n" + dnsAddress);
                    try {                    
                        Runtime.getRuntime().exec(ipAddresses);
                        Runtime.getRuntime().exec(dnsAddress);
            
                } catch (Exception e) {            
                }                
                break;            
        }
    }

    private void obtainAddresses() {
        netshToList.clear();
        
        IPAddress ip = new IPAddress();
        String address = "";
        String gateway = "";
        String dns = "";
        String mask = "";
        
        try {
            Process process = Runtime.getRuntime().exec("ipconfig /all");
            process.waitFor();

        BufferedReader reader = 
        new BufferedReader(new InputStreamReader(process.getInputStream(), "CP850"));
            
            String line = "";           
            System.out.println("\r\n***Comando IPCONFIG:***");
            while ((line = reader.readLine())!= null) {                    
                address = ip.getAdressIP(line);
                gateway = ip.getGateway(line);
                dns = ip.getDNS(line);
                mask = ip.getMask(line);                
                
                //MOSTRA AS INFORMAÇOES DO COMANDO MSDOS
                System.out.println(line);
                netshToList.add(line);                     
            }
            
            fillTextBoxes(address, mask, gateway, dns);            
            setAdapterName();            
        } 
        catch (Exception e) {
        }
    }

    private void setAdapterName() {
        //String nomeAdaptador;
        netshIndex.clear();
        try {
            for(int i = 0; i < netshToList.size();i++){
                if (netshToList.get(i).contains("Adaptador Ethernet")) {
                    netshIndex.add(i);
                }else if (netshToList.get(i).contains("Rede sem Fio")) {
                    netshIndex.add(i);
                }else if (netshToList.get(i).contains("IPv4")) {                
                    int index = netshIndex.size() - 1;
                    index = netshIndex.get(index); 
                    adapterName = netshToList.get(index);
                    adapterName = adapterName.replace("Adaptador Ethernet ", "");
                    adapterName = adapterName.replace("Adaptador de Rede sem Fio ", "");
                    adapterName = adapterName.replace(":", "");
                    //adapterName = StringUtils.abreviate("",5);
                    
                    //TODO: abreviar nome placa de rede
                    txtNetworkName.setText(adapterName);
//                    column.setHeaderValue(adapterName);
//                    tbIPAtual.getTableHeader().repaint();                    
                }            
            }                
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
    }

    private void changeFocus(JFormattedTextField txt) {
        String count = txt.getText().trim();
        if (count.length() == 3) { 
           KeyboardFocusManager manager = KeyboardFocusManager.getCurrentKeyboardFocusManager();
           manager.focusNextComponent();           
        }        
    }

    private ArrayList<Integer> convertIP(String address) {
        InetAddress ip;
        ArrayList<Integer> octet = new ArrayList<>();        
        try {
            ip = InetAddress.getByName(address);
            
            byte[] bytes = ip.getAddress();
                for (byte b : bytes) {
                //System.out.println(b & 0xFF);
                octet.add(b & 0xFF);                
            }
        } catch (UnknownHostException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
        return octet;
    }

    private void fillTextBoxes(String address, String mask, 
                               String gateway, String dns) {
        ArrayList<Integer> octet = convertIP(address);
        txtIP1.setText(octet.get(0).toString());
        txtIP2.setText(octet.get(1).toString());
        txtIP3.setText(octet.get(2).toString());
        txtIP4.setText(octet.get(3).toString());
            
        octet.clear();
        octet = convertIP(mask);
        txtIP5.setText(octet.get(0).toString());
        txtIP6.setText(octet.get(1).toString());
        txtIP7.setText(octet.get(2).toString());
        txtIP8.setText(octet.get(3).toString());
            
        octet.clear();
        octet = convertIP(gateway);
        txtIP9.setText(octet.get(0).toString());
        txtIP10.setText(octet.get(1).toString());
        txtIP11.setText(octet.get(2).toString());
        txtIP12.setText(octet.get(3).toString());
            
        octet.clear();
        octet = convertIP(dns);
        txtIP13.setText(octet.get(0).toString());
        txtIP14.setText(octet.get(1).toString());
        txtIP15.setText(octet.get(2).toString());
        txtIP16.setText(octet.get(3).toString());
    }
    
    private String[] getTextBoxesContent(){
        String[] addresses = new String[4];
        addresses[0] = txtIP1.getText() + ".";
        addresses[0] += txtIP2.getText() + ".";
        addresses[0] += txtIP3.getText() + ".";
        addresses[0] += txtIP4.getText();
        addresses[0] = addresses[0].replace(" ", "");
        
        addresses[1] = txtIP5.getText() + ".";
        addresses[1] += txtIP6.getText() + ".";
        addresses[1] += txtIP7.getText() + ".";
        addresses[1] += txtIP8.getText();
        addresses[1] = addresses[1].replace(" ", "");
        
        addresses[2] = txtIP9.getText() + ".";
        addresses[2] += txtIP10.getText() + ".";
        addresses[2] += txtIP11.getText() + ".";
        addresses[2] += txtIP12.getText();
        addresses[2] = addresses[2].replace(" ", "");
        
        addresses[3] = txtIP13.getText() + ".";
        addresses[3] += txtIP14.getText() + ".";
        addresses[3] += txtIP15.getText() + ".";
        addresses[3] += txtIP16.getText();
        addresses[3] = addresses[3].replace(" ", "");        
        
        return addresses;
    }

    private void changeEditable() {
        if (cbTipo.getSelectedIndex() == 3) {
            txtIP1.setEnabled(false);
            txtIP2.setEnabled(false);
            txtIP3.setEnabled(false);
            txtIP4.setEnabled(false);
            txtIP5.setEnabled(false);
            txtIP6.setEnabled(false);
            txtIP7.setEnabled(false);
            txtIP8.setEnabled(false);
            txtIP9.setEnabled(false);
            txtIP10.setEnabled(false);
            txtIP11.setEnabled(false);
            txtIP12.setEnabled(false);
            txtIP13.setEnabled(false);
            txtIP14.setEnabled(false);
            txtIP15.setEnabled(false);
            txtIP16.setEnabled(false);            
        }
        else{
            txtIP1.setEnabled(true);
            txtIP2.setEnabled(true);
            txtIP3.setEnabled(true);
            txtIP4.setEnabled(true);
            txtIP5.setEnabled(true);
            txtIP6.setEnabled(true);
            txtIP7.setEnabled(true);
            txtIP8.setEnabled(true);
            txtIP9.setEnabled(true);
            txtIP10.setEnabled(true);
            txtIP11.setEnabled(true);
            txtIP12.setEnabled(true);
            txtIP13.setEnabled(true);
            txtIP14.setEnabled(true);
            txtIP15.setEnabled(true);
            txtIP16.setEnabled(true); 
        }
    }
}
